packages:
  - "apps/*"
  - "packages/*"
publicHoistPattern:
  - pdfjs-dist
overrides:
  pdfjs-dist: 5.4.624
onlyBuiltDependencies:
  - esbuild
minimumReleaseAgeExclude:
  - "@paper-design/shaders-react@0.0.77"
  - "@paper-design/shaders@0.0.77"
allowBuilds:
  "@clerk/shared": false
  esbuild: true
  msw: true
