export const adminRoutePaths = [
  "/",
  "/auto-entries",
  "/billing",
  "/checklists",
  "/commissions",
  "/crm",
  "/customers",
  "/customize",
  "/custom-pages",
  "/dashboard",
  "/documents",
  "/expenses",
  "/fiscal",
  "/inventory",
  "/marketplaces",
  "/page-builder",
  "/paginas",
  "/paid-traffic",
  "/public-api",
  "/public-site",
  "/reports",
  "/sales",
  "/settings",
  "/simulations",
  "/site-publico",
] as const;
