import { z } from "zod";

export const CreateOwnerSubmissionSchema = z.object({
  ownerName: z.string().min(1),
  ownerEmail: z.string().email(),
  ownerPhone: z.string().min(1),
  ownerWhatsApp: z.string().optional(),
  ownerCpf: z.string().optional(),
  propertyType: z.string().min(1),
  propertyAddress: z.string().min(1),
  propertyCity: z.string().min(1),
  propertyState: z.string().default("SP"),
  price: z.number().optional(),
  rentPrice: z.number().optional(),
  cep: z.string().optional(),
  propertyStreet: z.string().optional(),
  propertyNumber: z.string().optional(),
  propertyComplement: z.string().optional(),
  propertyNeighborhood: z.string().optional(),
  propertyDescription: z.string().optional(),
  bedrooms: z.number().optional(),
  bathrooms: z.number().optional(),
  parkingSpots: z.number().optional(),
  area: z.number().optional(),
  purpose: z.string().default("VENDA"),
  photos: z.array(z.string()).optional(),
  preferredContact: z.string().default("WHATSAPP"),
  urgency: z.string().default("NORMAL"),
  howDidYouHear: z.string().optional(),
});

export const OwnerSubmissionSchema = z.object({
  id: z.string(),
  ownerName: z.string(),
  ownerEmail: z.string(),
  ownerPhone: z.string(),
  ownerWhatsApp: z.string().nullable().optional(),
  ownerCpf: z.string().nullable().optional(),
  propertyType: z.string(),
  propertyAddress: z.string(),
  propertyCity: z.string(),
  propertyState: z.string(),
  price: z.number().nullable().optional(),
  rentPrice: z.number().nullable().optional(),
  cep: z.string().nullable().optional(),
  propertyStreet: z.string().nullable().optional(),
  propertyNumber: z.string().nullable().optional(),
  propertyComplement: z.string().nullable().optional(),
  propertyNeighborhood: z.string().nullable().optional(),
  propertyDescription: z.string().nullable().optional(),
  bedrooms: z.number().nullable().optional(),
  bathrooms: z.number().nullable().optional(),
  parkingSpots: z.number().nullable().optional(),
  area: z.number().nullable().optional(),
  purpose: z.string(),
  photos: z.array(z.string()).nullable().optional(),
  preferredContact: z.string(),
  urgency: z.string(),
  howDidYouHear: z.string().nullable().optional(),
  status: z.string(),
  adminNotes: z.string().nullable().optional(),
  assignedAdminId: z.string().nullable().optional(),
  contactedAt: z.coerce.date().nullable().optional(),
  convertedPropertyId: z.string().nullable().optional(),
  linkedOwnerId: z.string().nullable().optional(),
  invitationSentAt: z.coerce.date().nullable().optional(),
  invitationError: z.string().nullable().optional(),
  retryCount: z.number(),
  invitationLastRetriedAt: z.coerce.date().nullable().optional(),
  utmSource: z.string().nullable().optional(),
  utmMedium: z.string().nullable().optional(),
  utmCampaign: z.string().nullable().optional(),
  ipAddress: z.string().nullable().optional(),
  userAgent: z.string().nullable().optional(),
  createdAt: z.coerce.date(),
});

export const UpdateOwnerSubmissionSchema = z.object({
  status: z.string().optional(),
  adminNotes: z.string().optional(),
  assignedAdminId: z.string().optional(),
  contactedAt: z.coerce.date().optional(),
});

export const CreatePropertyAssignmentSchema = z.object({
  propertyId: z.string().min(1),
  corretorNotes: z.string().optional(),
});

export const UpdatePropertyAssignmentSchema = z.object({
  status: z.enum(["APPROVED", "REJECTED", "REVOKED"]),
  reason: z.string().optional(),
});

export const RecordClosingSchema = z.object({
  assignmentId: z.string().min(1),
  salePrice: z.number().positive(),
  closingDate: z.coerce.date(),
  type: z.enum(["VENDA", "ALUGUEL"]),
  buyerName: z.string().min(1),
  buyerCpf: z.string().optional(),
  buyerPhone: z.string().optional(),
  financingType: z.enum(["CASH", "FINANCING", "FGTS", "MIXED"]),
});
