export const compoundNamedFamilies = [
  "c3 picasso",
  "c4 lounge",
  "c4 pallas",
  "c4 picasso",
  "c4 cactus",
  "corolla cross",
  "grand c4 picasso",
  "grand caravan",
  "grand cherokee",
  "grand siena",
  "land cruiser",
  "lt f160",
  "mustang mach-e",
  "onix sedan plus",
  "pt cruiser",
  "q6 e-tron",
  "q8 e-tron",
  "range rover",
  "range r. velar",
  "rs e-tron",
  "rs q3",
  "rs q8",
  "song pro",
  "série 3",
  "série 4",
  "série 5",
  "série 7",
  "xsara picasso",
];
