export const compoundFamilies = [
  "c3 picasso",
  "c4 lounge",
  "c4 pallas",
  "c4 picasso",
  "c4 cactus",
  "corolla cross",
  "grand c4 picasso",
  "grand caravan",
  "grand cherokee",
  "grand siena",
  "ix 3",
  "land cruiser",
  "mustang mach-e",
  "onix sedan plus",
  "pt cruiser",
  "q6 e-tron",
  "q8 e-tron",
  "range rover",
  "range r. velar",
  "rs e-tron",
  "rs q3",
  "rs q8",
  "serie 3",
  "serie 4",
  "serie 5",
  "serie 7",
  "song pro",
  "série 3",
  "série 4",
  "série 5",
  "série 7",
  "xsara picasso",
];

const markerTokenGroups = [
  "4x2 4x4 abarth absolute active activa adv adv. advance advanced",
  "advantage advanc advent advent. adventure allure allroad ambit ambit. ambiente ambition",
  "atacama attra attra. attracti attracti. attractive attraction audace",
  "autobiography avant black blackmotion bev break business cab cab.",
  "bau cabrio cabriolet cargo cd ce celeb celebration celeb. city class clx",
  "coach comfort connected coupe coupé competition comfortline compact crossroad cs csb csl",
  "c-series cult cupe cupê dark drive dual dualogic dynamic easy e-drive",
  "ed edx el edition edrive elx endurance entry economy elegant essence",
  "ex exc excl exclus exclusive exl excellence f family feel first freedom",
  "freestyle furg furgao furgão full gran gl gli gls glx gt ghia gs gsr hard",
  "hard-top hatch highline hgt hlx impulse intensive latitude launch le",
  "limited like live longitude lounge ls lt ltz luxo luxury lx m m-sport",
  "m.sport m40i m50 m50i mille minibus modern motorsport multiuso noir",
  "off open-top opening origine overland pack panel p p. perf performance perfor",
  "perfo perfo. performa performa. perform perform. performace perfornace",
  "picape pick-up pista platinum plus premium prest prestige premier precision pure quadrifoglio",
  "ranch rex rip road road. roadster rt s s-line salomon sb sb. sdrive",
  "se security seduction sed sed. sedan sel shine slx sdx spider spyder",
  "slt sportb sportb. sportback sport sporting spb spb. s-4 s2 srt8 std",
  "start storm street style super sw sxt titanium top touring tourer tendance tributo trendline",
  "trekking tropical tropicab tropivan turbo t-jet ultra un unique urban utility van",
  "vidrada vip vitre vitré volcano volante vts w wagon way week week. weekend working",
  "x-series x-line xei xl xline xls xlt xdrive xli xre xr3 xrx xtr",
];

export const variantMarkers = new Set(
  markerTokenGroups.flatMap((group) => group.split(/\s+/).filter(Boolean)),
);
