import type {
  EnsureFinanceAutoEntryRulesInput,
  FinanceAutoEntryRepository,
  FinanceAutoEntryRule,
} from "./ports/financeAutoEntryRepository.js";
import { financingStoreDefaults } from "./financeAutoEntryFinancingDefaults.js";

export const financeAutoEntryV1DefaultRuleKeys = {
  consortiumSeller: "consortium.seller",
  consortiumStore: "consortium.store",
  insuranceSeller: "insurance.seller",
  insuranceStore: "insurance.store",
  saleStandardCommission: "sale.standard_commission",
  transferCostLien: "transfer.cost.lien",
  transferCostNoLien: "transfer.cost.no_lien",
  transferRevenue: "transfer.revenue",
} as const;

const systemMetadata = {
  systemDefault: true,
  v1Parity: true,
  version: 1,
} as const;

export function buildV1FinanceAutoEntryDefaultRules(): EnsureFinanceAutoEntryRulesInput["rules"] {
  return [
    {
      calculation: {
        basis: "commission",
        basisPoints: 10_000,
        kind: "percentage",
      },
      category: "Comissão",
      conditions: {
        basisRange: { basis: "commission", minCents: 1 },
        standardCommissionEnabled: true,
      },
      event: "vehicle_sale_closed",
      family: financeAutoEntryV1DefaultRuleKeys.saleStandardCommission,
      metadata: {
        ...systemMetadata,
        policy: { product: "sale", source: "explicit_commission_snapshot" },
      },
      name: "Comissão padrão da venda",
      outputType: "commission",
      priority: 0,
      recipient: { kind: "event_seller" },
      resolution: "seller_override",
      ruleKey: financeAutoEntryV1DefaultRuleKeys.saleStandardCommission,
      sellerUserId: null,
      status: "active",
      timing: { kind: "same_day" },
    },
    ...financingStoreDefaults(),
    {
      calculation: { amountCents: 50_000, kind: "fixed" },
      category: "Documentação",
      conditions: { transferHasLien: false },
      event: "transfer_documentation_charged",
      family: "transfer.cost",
      metadata: {
        ...systemMetadata,
        policy: { product: "transfer", transferHasLien: false },
      },
      name: "Custo de transferência sem gravame",
      outputType: "expense",
      priority: 0,
      recipient: { kind: "none" },
      resolution: "additive",
      ruleKey: financeAutoEntryV1DefaultRuleKeys.transferCostNoLien,
      sellerUserId: null,
      status: "active",
      timing: { kind: "same_day" },
    },
    {
      calculation: { amountCents: 55_000, kind: "fixed" },
      category: "Documentação",
      conditions: { transferHasLien: true },
      event: "transfer_documentation_charged",
      family: "transfer.cost",
      metadata: {
        ...systemMetadata,
        policy: { product: "transfer", transferHasLien: true },
      },
      name: "Custo de transferência com gravame",
      outputType: "expense",
      priority: 0,
      recipient: { kind: "none" },
      resolution: "additive",
      ruleKey: financeAutoEntryV1DefaultRuleKeys.transferCostLien,
      sellerUserId: null,
      status: "active",
      timing: { kind: "same_day" },
    },
    {
      calculation: {
        basis: "documentation",
        kind: "rate_ppm",
        ratePpm: 1_000_000,
      },
      category: "Documentação",
      conditions: {},
      event: "transfer_documentation_charged",
      family: financeAutoEntryV1DefaultRuleKeys.transferRevenue,
      metadata: {
        ...systemMetadata,
        policy: { product: "transfer", storeSharePpm: 1_000_000 },
      },
      name: "Receita de documentação",
      outputType: "revenue",
      priority: 0,
      recipient: { kind: "none" },
      resolution: "additive",
      ruleKey: financeAutoEntryV1DefaultRuleKeys.transferRevenue,
      sellerUserId: null,
      status: "active",
      timing: { kind: "same_day" },
    },
    {
      calculation: {
        basis: "insurance_commission",
        kind: "rate_ppm",
        ratePpm: 500_000,
      },
      category: "Seguro",
      conditions: {},
      event: "insurance_issued",
      family: financeAutoEntryV1DefaultRuleKeys.insuranceStore,
      metadata: {
        ...systemMetadata,
        policy: {
          appliedCommissionPercentage: { default: 10, max: 20, min: 10 },
          product: "insurance",
          storeSharePpm: 500_000,
        },
      },
      name: "Receita da loja no seguro",
      outputType: "revenue",
      priority: 0,
      recipient: { kind: "none" },
      resolution: "additive",
      ruleKey: financeAutoEntryV1DefaultRuleKeys.insuranceStore,
      sellerUserId: null,
      status: "active",
      timing: { kind: "same_day" },
    },
    {
      calculation: { basis: "premium", kind: "rate_ppm", ratePpm: 7_500 },
      category: "Comissão",
      conditions: {},
      event: "insurance_issued",
      family: financeAutoEntryV1DefaultRuleKeys.insuranceSeller,
      metadata: {
        ...systemMetadata,
        policy: { product: "insurance", sellerRatePpm: 7_500 },
      },
      name: "Comissão do vendedor no seguro",
      outputType: "commission",
      priority: 0,
      recipient: { kind: "event_seller" },
      resolution: "seller_override",
      ruleKey: financeAutoEntryV1DefaultRuleKeys.insuranceSeller,
      sellerUserId: null,
      status: "active",
      timing: { kind: "same_day" },
    },
    {
      calculation: {
        basis: "consortium",
        kind: "rate_ppm",
        ratePpm: 18_500,
      },
      category: "Consórcio",
      conditions: {},
      event: "consortium_sold",
      family: financeAutoEntryV1DefaultRuleKeys.consortiumStore,
      metadata: {
        ...systemMetadata,
        policy: {
          product: "consortium",
          storeSharePpm: 500_000,
          totalRatePpm: 37_000,
        },
      },
      name: "Receita da loja no consórcio",
      outputType: "revenue",
      priority: 0,
      recipient: { kind: "none" },
      resolution: "additive",
      ruleKey: financeAutoEntryV1DefaultRuleKeys.consortiumStore,
      sellerUserId: null,
      status: "active",
      timing: { kind: "same_day" },
    },
    {
      calculation: { basis: "consortium", kind: "rate_ppm", ratePpm: 2_770 },
      category: "Comissão",
      conditions: {},
      event: "consortium_sold",
      family: financeAutoEntryV1DefaultRuleKeys.consortiumSeller,
      metadata: {
        ...systemMetadata,
        policy: {
          product: "consortium",
          sellerRatePpm: 2_770,
          totalRatePpm: 37_000,
        },
      },
      name: "Comissão do vendedor no consórcio",
      outputType: "commission",
      priority: 0,
      recipient: { kind: "event_seller" },
      resolution: "seller_override",
      ruleKey: financeAutoEntryV1DefaultRuleKeys.consortiumSeller,
      sellerUserId: null,
      status: "active",
      timing: { kind: "same_day" },
    },
  ];
}

export async function ensureV1FinanceAutoEntryDefaultRules(
  repository: FinanceAutoEntryRepository,
  scope: { storeId: string | null; tenantId: string | null },
): Promise<readonly FinanceAutoEntryRule[]> {
  return repository.ensureRules({
    rules: buildV1FinanceAutoEntryDefaultRules(),
    ...scope,
  });
}
