import { createDocumentPdfStyles } from "../../documents/render/reactPdfDocumentStyles.js";

export const executiveReportStyles = createDocumentPdfStyles({
  page: {
    backgroundColor: "#f8fafc",
    color: "#172033",
    fontFamily: "Helvetica",
    fontSize: 9,
    paddingBottom: 46,
    paddingHorizontal: 34,
    paddingTop: 34,
  },
  header: {
    backgroundColor: "#101827",
    borderRadius: 8,
    color: "#ffffff",
    marginBottom: 18,
    padding: 18,
  },
  eyebrow: {
    color: "#7dd3fc",
    fontFamily: "Helvetica-Bold",
    fontSize: 8,
    letterSpacing: 1.4,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  title: {
    fontFamily: "Helvetica-Bold",
    fontSize: 22,
    marginBottom: 6,
  },
  subtitle: { color: "#cbd5e1", fontSize: 10 },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 18,
  },
  metric: {
    backgroundColor: "#ffffff",
    borderColor: "#dbe4ee",
    borderRadius: 6,
    borderWidth: 1,
    minHeight: 58,
    padding: 10,
    width: "31.9%",
  },
  metricLabel: {
    color: "#64748b",
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
    marginBottom: 5,
    textTransform: "uppercase",
  },
  metricValue: {
    color: "#0f172a",
    fontFamily: "Helvetica-Bold",
    fontSize: 14,
  },
  section: { marginBottom: 16 },
  sectionTitle: {
    color: "#0f172a",
    fontFamily: "Helvetica-Bold",
    fontSize: 12,
    marginBottom: 8,
  },
  summaryRow: {
    backgroundColor: "#ffffff",
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  summaryLabel: { color: "#475569" },
  summaryValue: {
    color: "#0f172a",
    fontFamily: "Helvetica-Bold",
  },
  tableHeader: {
    backgroundColor: "#e8eef5",
    flexDirection: "row",
    paddingHorizontal: 6,
    paddingVertical: 7,
  },
  tableRow: {
    backgroundColor: "#ffffff",
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    flexDirection: "row",
    paddingHorizontal: 6,
    paddingVertical: 7,
  },
  tableHeaderText: {
    color: "#475569",
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
    textTransform: "uppercase",
  },
  tableText: { color: "#1e293b", fontSize: 8 },
  mutedText: { color: "#64748b", fontSize: 7 },
  warning: {
    backgroundColor: "#fff7ed",
    borderColor: "#fed7aa",
    borderRadius: 5,
    borderWidth: 1,
    color: "#9a3412",
    marginBottom: 16,
    padding: 9,
  },
  footer: {
    bottom: 20,
    color: "#94a3b8",
    fontSize: 7,
    left: 34,
    position: "absolute",
    right: 34,
    textAlign: "center",
  },
});
