import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PDFDocument } from "pdf-lib";
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
import { describe, expect, it } from "vitest";
import "../db/reset-local-databases-core.test.mjs";
import "../qa/local-seed-smoke-providers.test.mjs";
import {
  createSeedDocumentArtifact,
  sha256SeedDocumentBytes,
} from "./seed-product-document-artifact.mjs";
import {
  renderSeedDocumentPdf,
  SEED_DOCUMENT_ARTIFACT_VERSION,
  shouldRefreshSeedDocumentArtifact,
} from "./seed-product-document-pdf.mjs";
import "./seed-product-media-placeholder.test.mjs";
import "./storageScriptEnv.test.mjs";

const seededPayment = {
  documentId: "51000000-0000-4000-8000-000000000005",
  fileName: "recibo-pagamento-hilux.pdf",
  kind: "finance_receipt",
  metadata: {
    amountCents: 4000000,
    buyerName: "Carla Rocha",
    financeTitle: "Pagamento de entrada",
    listingId: "10000000-0000-4000-8000-000000000004",
    method: "Pix",
    paymentId: "32000000-0000-4000-8000-000000000001",
    plate: "JKL0M12",
    vehicleTitle: "Toyota Hilux SRX 2021",
  },
  status: "issued",
  storageKey: "seed/documents/recibo-pagamento-hilux.pdf",
  storeAddressLine: "Avenida Loja V2, 1000",
  storeCity: "São Paulo",
  storeDocumentNumber: "00000000000100",
  storeName: "Loja Teste",
  storePhone: "+5511999999999",
  storeState: "SP",
  title: "Comprovante de pagamento",
};

describe("seed product document PDF", () => {
  it("derives the visible and embedded issue date from the seeded document", async () => {
    const bytes = await renderSeedDocumentPdf({
      ...seededPayment,
      issuedAt: new Date("2026-07-03T19:45:00.000Z"),
    });
    const pdf = await PDFDocument.load(bytes);
    const text = await extractPdfText(bytes);

    expect(text).toContain("3 de julho de 2026");
    expect(pdf.getCreationDate()).toEqual(new Date("2026-07-03T12:00:00.000Z"));
  });

  it("refreshes only stale local seed fixtures", () => {
    expect(
      shouldRefreshSeedDocumentArtifact({ fixture: "local-product-seed" }),
    ).toBe(true);
    expect(
      shouldRefreshSeedDocumentArtifact({
        artifactversion: SEED_DOCUMENT_ARTIFACT_VERSION,
        fixture: "local-product-seed",
      }),
    ).toBe(false);
    expect(shouldRefreshSeedDocumentArtifact({})).toBe(false);
    expect(
      shouldRefreshSeedDocumentArtifact({ fixture: "vehicle-workflow" }),
    ).toBe(false);
    expect(
      shouldRefreshSeedDocumentArtifact(
        {},
        { storageKey: "seed/documents/owned.pdf" },
      ),
    ).toBe(true);
    expect(
      shouldRefreshSeedDocumentArtifact(
        {
          artifactsha256: "stored-hash",
          artifactversion: SEED_DOCUMENT_ARTIFACT_VERSION,
        },
        {
          expectedSha256: "generated-hash",
          storageKey: "seed/documents/owned.pdf",
        },
      ),
    ).toBe(true);
  });

  it("matches the generated byte hash recorded for a stored fixture", async () => {
    const artifact = await createSeedDocumentArtifact(seededPayment);
    const directory = await mkdtemp(join(tmpdir(), "lv-seed-document-"));
    try {
      const artifactPath = join(directory, seededPayment.fileName);
      await writeFile(artifactPath, artifact.body);
      const storedHash = sha256SeedDocumentBytes(await readFile(artifactPath));

      expect(storedHash).toBe(artifact.sha256);
      expect(
        shouldRefreshSeedDocumentArtifact(
          {
            artifactsha256: storedHash,
            artifactversion: SEED_DOCUMENT_ARTIFACT_VERSION,
          },
          {
            expectedSha256: artifact.sha256,
            storageKey: seededPayment.storageKey,
          },
        ),
      ).toBe(false);
    } finally {
      await rm(directory, { force: true, recursive: true });
    }
  });

  it.each([
    ["sale_contract", "Contrato de compra e venda"],
    ["reservation_receipt", "Recibo de reserva"],
    ["sale_receipt", "Recibo de venda"],
    ["delivery_term", "Termo de entrega do veículo"],
    ["power_of_attorney", "Procuração para transferência"],
    ["inspection", "Laudo cautelar"],
    ["internal", "Protocolo de atendimento"],
    ["finance_receipt", "Comprovante de pagamento"],
  ])(
    "renders the %s seed kind as a canonical document",
    async (kind, title) => {
      const bytes = await renderSeedDocumentPdf({
        ...seededPayment,
        kind,
        title: "Documento demonstrativo",
      });
      const pdf = await PDFDocument.load(bytes);
      expect(pdf.getTitle()).toBe(title);
      expect(pdf.getPageCount()).toBe(1);
    },
  );

  it("renders a deterministic branded A4 document", async () => {
    const first = await renderSeedDocumentPdf(seededPayment);
    const second = await renderSeedDocumentPdf(seededPayment);
    expect(Buffer.from(first)).toEqual(Buffer.from(second));

    const pdf = await PDFDocument.load(first);
    const [page] = pdf.getPages();
    expect(page?.getWidth()).toBeCloseTo(595.28, 1);
    expect(page?.getHeight()).toBeCloseTo(841.89, 1);
    expect(pdf.getTitle()).toBe("Comprovante de pagamento");
    expect(pdf.getAuthor()).toBe("Loja Teste");
  });

  it("shows human-facing business data without internal identifiers", async () => {
    const bytes = await renderSeedDocumentPdf(seededPayment);
    const text = await extractPdfText(bytes);

    expect(text).toContain("Loja Teste");
    expect(text).toContain("Comprovante de pagamento");
    expect(text).toContain("Carla Rocha");
    expect(text).toContain("Toyota Hilux SRX 2021");
    expect(text).toContain("JKL0M12");
    expect(text).toContain("VALOR RECEBIDO");
    expect(text).toContain("R$ 40.000,00");
    expect(text).toContain("AMBIENTE DE DEMONSTRAÇÃO");
    expect(text).not.toMatch(/[0-9a-f]{8}-[0-9a-f-]{27,}/i);
    expect(text).not.toContain(seededPayment.documentId);
    expect(text).not.toContain(seededPayment.storageKey);
    expect(text).not.toContain("Storage key");
    expect(text).not.toContain("Local seed document fixture");
  });
});

async function extractPdfText(bytes) {
  const loadingTask = getDocument({
    data: Uint8Array.from(bytes),
    useSystemFonts: true,
  });
  const pdf = await loadingTask.promise;
  const pages = [];
  for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber += 1) {
    const page = await pdf.getPage(pageNumber);
    const content = await page.getTextContent();
    pages.push(
      content.items.map((item) => ("str" in item ? item.str : "")).join(" "),
    );
  }
  await pdf.destroy();
  return pages.join("\n");
}
