export const openApiScopes = {
  "analytics.read": "Read commercial analytics dashboards.",
  "compliance.manage": "Read and operate LGPD/security posture controls.",
  "fiscal.manage": "Operate fiscal provider and NF-e document lifecycle.",
  "finance.read": "Read finance entries, summaries, and rules.",
  "finance.create": "Create finance entries, recurring entries, and rules.",
  "finance.update": "Update, pay, cancel, and void finance entries.",
  "finance.attach_document":
    "Request uploads and attach documents to finance entries.",
  "finance.auto_entries.manage":
    "Create, update, pause, and archive automatic finance entry rules.",
  "inventory.read": "Read vehicle inventory.",
  "inventory.create": "Create vehicle inventory records.",
  "inventory.update_description": "Edit descriptive vehicle fields.",
  "inventory.update_commercial_tags": "Edit public vehicle listing tags.",
  "inventory.update_internal_notes": "Edit internal vehicle notes.",
  "inventory.update_price": "Edit vehicle pricing.",
  "inventory.update_status": "Edit vehicle listing lifecycle status.",
  "inventory.update_unit": "Edit physical/unit inventory fields.",
  "inventory.update_video": "Edit the public vehicle listing video.",
  "inventory.ai_studio_generate":
    "Generate AI studio images and approve gallery attachment.",
  "inventory.media_update": "Reorder media and edit media visibility.",
  "inventory.media_delete": "Delete vehicle media and cleanup objects.",
  "inventory.cost_create": "Create vehicle costs and linked finance entries.",
  "inventory.checklist_read": "Read vehicle readiness checklists.",
  "inventory.checklist_update":
    "Create and update vehicle readiness checklists.",
  "inventory.reserve":
    "Reserve, release, cancel, or expire vehicle unit reservations.",
  "inventory.sell": "Sell vehicle units and emit sale document bundles.",
  "inventory.delete": "Delete vehicle inventory records.",
  "documents.read": "Read shared store-scoped documents.",
  "documents.download": "Generate scoped document download descriptors.",
  "documents.preview": "Render scoped document previews.",
  "documents.regenerate": "Regenerate scoped operational documents.",
  "documents.update_links": "Change scoped document store/unit links.",
  "documents.void": "Void scoped documents.",
  "marketplace.read": "Read OLX/Mercado Livre account and sync status.",
  "marketplace.manage": "Connect or pause marketplace accounts.",
  "marketplace.inventory_sync": "Queue marketplace inventory sync jobs.",
  "marketplace.lead_sync": "Queue marketplace lead import jobs.",
  "marketplace.listing_publish": "Queue listing publish jobs.",
  "marketplace.listing_update": "Queue listing update jobs.",
  "marketplace.listing_unpublish": "Queue listing unpublish jobs.",
} as const;
