import { describe, expect, it } from "vitest";
import { providerCapabilities } from "./whatsappConnectionModels.js";

describe("CRM provider capabilities", () => {
  it.each([
    [
      "zapi",
      {
        audio: true,
        catalog: true,
        conversationStart: true,
        delete: true,
        documents: true,
        imageCaption: true,
        images: true,
        location: true,
        quickMessages: true,
        reactions: true,
        reply: true,
        scheduling: true,
        templates: false,
        text: true,
        vehicle: true,
        video: true,
      },
    ],
    [
      "composio_whatsapp",
      {
        audio: true,
        catalog: false,
        conversationStart: true,
        delete: false,
        documents: true,
        imageCaption: true,
        images: true,
        location: true,
        quickMessages: true,
        reactions: false,
        reply: true,
        scheduling: false,
        templates: true,
        text: true,
        vehicle: true,
        video: true,
      },
    ],
    [
      "composio_instagram",
      {
        audio: false,
        catalog: false,
        conversationStart: false,
        delete: false,
        documents: false,
        imageCaption: false,
        images: true,
        location: false,
        quickMessages: false,
        reactions: false,
        reply: false,
        scheduling: false,
        templates: false,
        text: true,
        vehicle: false,
        video: false,
      },
    ],
    [
      "olx_chat",
      {
        audio: false,
        catalog: false,
        conversationStart: false,
        delete: false,
        documents: false,
        imageCaption: false,
        images: false,
        location: false,
        quickMessages: false,
        reactions: false,
        reply: false,
        scheduling: false,
        templates: false,
        text: true,
        vehicle: false,
        video: false,
      },
    ],
  ] as const)("reports the complete %s action matrix", (provider, expected) => {
    expect(providerCapabilities(provider)).toEqual(expected);
  });
});
