import { createDocumentPdfStyles } from "../../documents/render/reactPdfDocumentStyles.js";
import type { VehicleChecklistOverviewStatus } from "../readModels/vehicleChecklistOverview.js";

/**
 * Checklist report styles ported from the V1 VehicleChecklistPDF and
 * VehicleChecklistSummaryPDF documents (soft gray cards, green/red badges).
 */
export const checklistStyles = createDocumentPdfStyles({
  page: {
    backgroundColor: "#ffffff",
    color: "#1f2937",
    fontFamily: "Helvetica",
    fontSize: 10,
    padding: 40,
  },
  header: {
    alignItems: "center",
    borderBottomColor: "#e5e7eb",
    borderBottomWidth: 1,
    flexDirection: "column",
    marginBottom: 20,
    paddingBottom: 20,
  },
  logoBox: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    width: "100%",
  },
  logo: { maxHeight: 80, maxWidth: 200, objectFit: "contain" },
  title: {
    color: "#111827",
    fontFamily: "Helvetica-Bold",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 4,
    textAlign: "center",
  },
  subtitle: { color: "#6b7280", fontSize: 10, textAlign: "center" },
  section: { marginBottom: 24 },
  sectionTitle: {
    color: "#111827",
    fontFamily: "Helvetica-Bold",
    fontSize: 14,
    fontWeight: "bold",
    letterSpacing: 0.5,
    marginBottom: 12,
    textTransform: "uppercase",
  },
  infoGrid: {
    backgroundColor: "#f9fafb",
    borderColor: "#e5e7eb",
    borderRadius: 8,
    borderWidth: 1,
  },
  row: {
    borderBottomColor: "#e5e7eb",
    borderBottomWidth: 1,
    flexDirection: "row",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  lastRow: { borderBottomWidth: 0 },
  label: { color: "#6b7280", fontSize: 10, width: "40%" },
  value: {
    color: "#111827",
    fontFamily: "Helvetica-Bold",
    fontSize: 10,
    fontWeight: "bold",
    width: "60%",
  },
  checklistItem: {
    alignItems: "center",
    borderBottomColor: "#e5e7eb",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  checklistLabel: { color: "#374151", fontSize: 11 },
  statusBadge: {
    borderRadius: 4,
    fontFamily: "Helvetica-Bold",
    fontSize: 9,
    paddingHorizontal: 10,
    paddingVertical: 4,
    textTransform: "uppercase",
  },
  statusYes: { backgroundColor: "#dcfce7", color: "#166534" },
  statusNo: { backgroundColor: "#fee2e2", color: "#991b1b" },
  statusNeutral: { backgroundColor: "#f3f4f6", color: "#374151" },
  completionText: {
    color: "#10b981",
    fontFamily: "Helvetica-Bold",
    fontSize: 11,
    fontWeight: "bold",
  },
  progressBarContainer: {
    backgroundColor: "#e5e7eb",
    borderRadius: 3,
    height: 6,
    marginTop: 8,
    overflow: "hidden",
  },
  progressBarFill: {
    backgroundColor: "#10b981",
    borderRadius: 3,
    height: "100%",
  },
  notesBox: {
    backgroundColor: "#ffffff",
    borderColor: "#e5e7eb",
    borderRadius: 8,
    borderWidth: 1,
    color: "#374151",
    lineHeight: 1.5,
    minHeight: 80,
    padding: 16,
  },
  footer: {
    borderTopColor: "#f3f4f6",
    borderTopWidth: 1,
    bottom: 30,
    color: "#9ca3af",
    fontSize: 9,
    left: 40,
    paddingTop: 12,
    position: "absolute",
    right: 40,
    textAlign: "center",
  },
});

export const fleetStyles = createDocumentPdfStyles({
  page: {
    backgroundColor: "#ffffff",
    color: "#1f2937",
    fontFamily: "Helvetica",
    fontSize: 9,
    padding: 30,
  },
  header: {
    alignItems: "center",
    borderBottomColor: "#e5e7eb",
    borderBottomWidth: 1,
    flexDirection: "column",
    marginBottom: 20,
    paddingBottom: 16,
  },
  logoBox: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    width: "100%",
  },
  logo: { maxHeight: 60, maxWidth: 180, objectFit: "contain" },
  title: {
    color: "#111827",
    fontFamily: "Helvetica-Bold",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 4,
    textAlign: "center",
  },
  subtitle: { color: "#6b7280", fontSize: 10, textAlign: "center" },
  sectionTitle: {
    color: "#111827",
    fontFamily: "Helvetica-Bold",
    fontSize: 12,
    fontWeight: "bold",
  },
  tableHeader: {
    backgroundColor: "#f9fafb",
    borderBottomWidth: 1,
    borderColor: "#e5e7eb",
    borderTopWidth: 1,
    flexDirection: "row",
    paddingHorizontal: 4,
    paddingVertical: 8,
  },
  tableRow: {
    alignItems: "center",
    borderBottomColor: "#f3f4f6",
    borderBottomWidth: 1,
    flexDirection: "row",
    paddingHorizontal: 4,
    paddingVertical: 8,
  },
  th: {
    color: "#4b5563",
    fontFamily: "Helvetica-Bold",
    fontSize: 8,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  td: { color: "#111827", fontSize: 9 },
  statusBadge: {
    backgroundColor: "#f3f4f6",
    borderRadius: 2,
    color: "#374151",
    fontFamily: "Helvetica-Bold",
    fontSize: 8,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  statusYes: { color: "#10b981" },
  statusNo: { color: "#ef4444" },
  footer: {
    borderTopColor: "#f3f4f6",
    borderTopWidth: 1,
    bottom: 20,
    color: "#9ca3af",
    fontSize: 8,
    left: 30,
    paddingTop: 10,
    position: "absolute",
    right: 30,
    textAlign: "center",
  },
});

export function overviewStatusLabel(status: VehicleChecklistOverviewStatus) {
  return {
    failed: "Com reprovação",
    in_progress: "Em andamento",
    missing: "Sem checklist",
    passed: "Concluído",
    pending: "Pendente",
    waived: "Dispensado",
  }[status];
}
