import { createDocumentPdfStyles } from "../../documents/render/reactPdfDocumentStyles.js";

/** V1 ProcuracaoVeiculoTroca layout styles. */
export const procuracaoStyles = createDocumentPdfStyles({
  header: {
    alignItems: "center",
    borderBottomColor: "#dddddd",
    borderBottomWidth: 1,
    flexDirection: "column",
    marginBottom: 20,
    paddingBottom: 15,
  },
  headerTop: { alignItems: "center", marginBottom: 10, width: "100%" },
  headerBottom: {
    alignItems: "flex-end",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  storeInfo: { flex: 1 },
  storeName: {
    fontSize: 12,
    fontWeight: "bold",
    marginBottom: 3,
    textTransform: "uppercase",
  },
  storeDetail: { color: "#000000", fontSize: 9, marginBottom: 1 },
  titleSection: { alignItems: "center", marginBottom: 20 },
  mainTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 5,
    textAlign: "center",
  },
  section: { marginBottom: 15 },
  sectionTitle: { fontSize: 11, fontWeight: "bold", marginBottom: 8 },
  paragraph: {
    fontSize: 10,
    lineHeight: 1.4,
    marginBottom: 8,
    textAlign: "justify",
  },
  vehicleBox: {
    borderColor: "#333333",
    borderWidth: 1,
    marginBottom: 8,
    marginTop: 8,
    padding: 12,
  },
  vehicleRow: { flexDirection: "row", marginBottom: 4 },
  vehicleLabel: { fontSize: 10, fontWeight: "bold", width: 90 },
  vehicleValue: { flex: 1, fontSize: 10 },
  listItem: {
    fontSize: 10,
    marginBottom: 4,
    paddingLeft: 10,
    textAlign: "justify",
  },
  signatureSection: { marginBottom: 20, marginTop: 35 },
  signatureLine: {
    borderTopColor: "#333333",
    borderTopWidth: 1,
    marginBottom: 5,
    marginTop: 8,
    paddingTop: 40,
  },
  signatureNameAbove: { fontSize: 10, marginBottom: 4, textAlign: "center" },
  signatureText: { fontSize: 9, textAlign: "center" },
  footer: {
    borderTopColor: "#dddddd",
    borderTopWidth: 1,
    bottom: 25,
    flexDirection: "row",
    justifyContent: "space-between",
    left: 30,
    paddingTop: 8,
    position: "absolute",
    right: 30,
  },
  footerText: { color: "#666666", fontSize: 8 },
});
