import { StyleSheet } from "@react-pdf/renderer";

export const createDocumentPdfStyles = StyleSheet.create;

export const styles = StyleSheet.create({
  body: { gap: 14 },
  brandCopy: { flex: 1, gap: 3 },
  clause: {
    borderLeftColor: "#e11f26",
    borderLeftWidth: 2,
    paddingLeft: 10,
  },
  clauseLabel: {
    color: "#b81820",
    fontSize: 8,
    fontWeight: 700,
    marginBottom: 3,
  },
  clauseOpening: { gap: 8 },
  clauseText: { color: "#151515", fontSize: 9.5, lineHeight: 1.5 },
  documentTitle: { alignItems: "flex-end", flex: 1.1, gap: 4 },
  field: {
    backgroundColor: "#f4efee",
    borderColor: "#e8e3e2",
    borderWidth: 1,
    padding: 9,
    width: "48%",
  },
  fieldGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  fieldLabel: {
    color: "#4a4444",
    fontSize: 7,
    fontWeight: 700,
    marginBottom: 3,
  },
  fieldValue: { color: "#151515", fontSize: 9, lineHeight: 1.35 },
  footer: {
    borderTopColor: "#e8e3e2",
    borderTopWidth: 1,
    bottom: 28,
    flexDirection: "row",
    justifyContent: "space-between",
    left: 42,
    position: "absolute",
    right: 42,
  },
  header: {
    alignItems: "center",
    backgroundColor: "#151515",
    borderBottomColor: "#e11f26",
    borderBottomWidth: 3,
    flexDirection: "row",
    gap: 12,
    left: 42,
    padding: 14,
    position: "absolute",
    right: 42,
    top: 32,
  },
  headerMuted: { color: "#a09898", fontSize: 7.5 },
  headerTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: 700,
    textAlign: "right",
  },
  intro: { color: "#151515", fontSize: 10, lineHeight: 1.5 },
  logoMark: {
    alignItems: "center",
    backgroundColor: "#e11f26",
    color: "#ffffff",
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  muted: { color: "#4a4444", fontSize: 7.5 },
  page: { backgroundColor: "#ffffff", padding: "124 42 64" },
  section: { gap: 8 },
  sectionCompact: { gap: 8, marginTop: 2 },
  sectionTitle: {
    borderBottomColor: "#e8e3e2",
    borderBottomWidth: 1,
    color: "#151515",
    fontSize: 9,
    fontWeight: 700,
    paddingBottom: 4,
    textTransform: "uppercase",
  },
  signature: { gap: 5, width: "46%" },
  signatureLabel: { color: "#151515", fontSize: 8, fontWeight: 700 },
  signatureLine: { borderTopColor: "#151515", borderTopWidth: 1 },
  signatures: {
    flexDirection: "row",
    gap: 24,
    justifyContent: "space-between",
    marginTop: 28,
  },
  storeName: { color: "#ffffff", fontSize: 10, fontWeight: 700 },
});
