import type { AuditSink } from "@lojaveiculosv2/audit";
import type { AnalyticsServices } from "../../features/analytics/controllers/analyticsServices.js";
import type { BillingServices } from "../../features/billing/controllers/billingServices.js";
import type { ComplianceServices } from "../../features/compliance/controllers/complianceServices.js";
import type { CrmRealtimeBroker } from "../../domains/crm/ports/crmRealtimePublisher.js";
import type { CrmServices } from "../../features/crm/controllers/crmServices.js";
import type { DocumentServices } from "../../features/documents/controllers/documentServices.js";
import type { ExternalApiServices } from "../../features/externalApi/controllers/externalApiServices.js";
import type { FinanceServices } from "../../features/finance/controllers/financeServices.js";
import type { FiscalServices } from "../../features/fiscal/controllers/fiscalServices.js";
import type { AccountProvisioningServices } from "../../features/identity/controllers/accountProvisioningServices.js";
import type { RoleServices } from "../../features/identity/controllers/roleServices.js";
import type { InternalMonitoringServices } from "../../features/internal/controllers/internalMonitoringServices.js";
import type { InventoryEnrichmentServices } from "../../features/inventory/controllers/inventoryEnrichmentServices.js";
import type { InventoryListingServices } from "../../features/inventory/controllers/listingServices.js";
import type { MarketplaceServices } from "../../features/marketplaces/controllers/marketplaceServices.js";
import type { SalesServices } from "../../features/sales/controllers/salesServices.js";
import type { SettingsServices } from "../../features/settings/controllers/settingsServices.js";
import type { StorefrontMediaServices } from "../../features/storefront/controllers/storefrontMediaServices.js";
import type { CrmRepository } from "../../domains/crm/ports/crmRepository.js";
import type { ExternalApiRepository } from "../../domains/externalApi/ports/externalApiRepository.js";
import type { StoreAccessRepository } from "../../domains/identity/ports/storeAccessRepository.js";
import type { PublicStorefrontRepository } from "../../domains/storefront/ports/publicStorefrontRepository.js";
import type { StorefrontPageRepository } from "../../domains/storefront/ports/storefrontPageRepository.js";
import type { ClerkUserProfileProvider } from "../auth/clerkAccountProvisioning.js";
import type { HttpIdentityVerifier } from "./httpIdentityVerifier.js";

export type CreateAppOptions = {
  analyticsServices?: AnalyticsServices;
  audit?: AuditSink;
  accountProvisioningServices?: AccountProvisioningServices;
  billingServices?: BillingServices;
  complianceServices?: ComplianceServices;
  crmRealtimeBroker?: CrmRealtimeBroker;
  crmServices?: CrmServices;
  documentServices?: DocumentServices;
  externalApiRepository?: ExternalApiRepository;
  externalApiServices?: ExternalApiServices;
  financeServices?: FinanceServices;
  fiscalServices?: FiscalServices;
  identityVerifier?: HttpIdentityVerifier;
  clerkUserProfileProvider?: ClerkUserProfileProvider;
  internalMonitoringServices?: InternalMonitoringServices;
  marketplaceServices?: MarketplaceServices;
  inventoryEnrichmentServices?: InventoryEnrichmentServices;
  inventoryListingServices?: InventoryListingServices;
  publicStorefrontRepository?: PublicStorefrontRepository;
  storefrontPageRepository?: StorefrontPageRepository;
  storefrontMediaServices?: StorefrontMediaServices;
  publicStorefrontCrmRepository?: CrmRepository;
  roleServices?: RoleServices;
  salesServices?: SalesServices;
  settingsServices?: SettingsServices;
  storeAccessRepository?: StoreAccessRepository;
};
